name: Enterprise Release Pipeline

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-22.04

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deterministic dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --require-hashes -r requirements.txt || echo "No pinned requirements"

      - name: Generate SBOM
        run: |
          python -m pip install cyclonedx-bom
          cyclonedx-py requirements -o sbom.xml || echo "SBOM skipped"

      - name: Create release artifact
        run: |
          mkdir -p dist
          cp spec/full-spec.md dist/
          sha256sum dist/full-spec.md > dist/full-spec.sha256

      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: enterprise-release
          path: dist/